language: node_js
node_js: "4"

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  chrome: stable
  apt:
    packages:
     fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sleep 3

script: "npm run-script test"
